version: '2.3'

services:
  prism:
    build:
      context: ./backend_service/
      dockerfile: Dockerfile
    image: prism
    container_name: prism
    environment:
      NVIDIA_VISIBLE_DEVICES: "0"
      MKL_SERVICE_FORCE_INTEL: "1"
      TORCH_USE_CUDA_DSA: "1"
      CUDA_LAUNCH_BLOCKING: "1"
    ports:
      - "7500:80"
    volumes:
       - ./models:/app/models
       - ./outputs:/app/outputs
       - ./shared:/app/shared
    runtime: nvidia
    networks:
      - prism-network

  prism-stream:
    build:
      context: ./stream_service/
      dockerfile: Dockerfile
    image: prism-stream
    container_name: prism-stream
    ports:
      - "7550:80"
      - "5554:5554"
    volumes:
       - ./shared:/app/shared
    runtime: nvidia
    networks:
      - prism-network

networks:
  prism-network:
    external: true